// (i).How to Start Game? 
// press any key on the document to start the game 

// we will add random colors generated by game to the gameSeq array 
let gameSeq = [];  
let userSeq = [];
let buttons = ["yellow", "red", "purple", "green"];
let h2 = document.querySelector("h2");
let p = document.querySelector("p");

let isStarted = false;
let level = 0;
let hightestLevel = 0;

// start game 
// press any key on the document to start the game 
document.addEventListener("keypress", function(){
    if(isStarted == false){
        console.log("Game Started");
        p.innerHTML = ``;
        isStarted = true;
        levelUp();
    }
})

// (ii). Level 1 + button flash after starting game 
// because we have to flash the button again and again so we make it a function for it 
function buttonFlash(btn){
    btn.classList.add("flash");
    setTimeout(function(){
        btn.classList.remove("flash");
    }, 300);
    // After flashing Random Button game will wait till user click any of the four button 
}

//This function level up the game and flash the random button
function levelUp(){
    userSeq = [];
    level++;
    hightestLevel++;
    h2.innerText = `Current Level ${level}`;

    // now we have make random button flash 
    let randomIdx = Math.floor(Math.random() * 4);
    let randomColor = buttons[randomIdx];
    let randomButton = document.querySelector(`.${randomColor}`);
    // console.log(randomIdx);
    // console.log(randomColor);
    // console.log(randomButton);

    gameSeq.push(randomColor);
    console.log(gameSeq);
    buttonFlash(randomButton);
}
function correctEffect(){
    let body = document.querySelector("body");
    body.classList.add("correctEffect");

    setTimeout(function(){
        body.classList.remove("correctEffect");
    }, 150);
}

function incorrectEffect(){
    let body = document.querySelector("body");
    body.classList.add("incorrectEffect");

    setTimeout(function(){
        body.classList.remove("incorrectEffect");
    }, 150);
}

// (iii). track game sequence and user sequence of choices of pressing button
// array sequence to track game button flash sequence
// another array sequence of user to track user button click sequence restart at each level

function checkButton(idx){
    // console.log("curr level: ", level);
    
    // (iv). check if button press by user is correct to the game sequence 
    if(userSeq[idx] == gameSeq[idx]){
        correctEffect();
        if(userSeq.length == gameSeq.length){
            // (v). if sequence match then level up 
            setTimeout(levelUp, 1100);
        }
    } else {
        // (vi). if not then game over and print the score 
        incorrectEffect();
        if(hightestLevel > level){
            h2.innerHTML = `GAME OVER! Your Highest Score is <b>${hightestLevel}</b> <br> Press any key to restart`;
        } else {
            h2.innerHTML = `GAME OVER! Your Score is <b>${level}</b> <br> Press any key to restart`;
        }
        reset();
    }
}

function buttonPress(){
    if(isStarted == false){
        incorrectEffect();
        p.innerHTML = `<b>What are you doing bruh</b> <br> First click any random keyboard button to start the game`;
    } else{
        console.log(this);
        let btn = this;
        // userButtonFlash(btn);

        let userButtonColor = btn.getAttribute("id");
        userSeq.push(userButtonColor);

        checkButton(userSeq.length - 1);
    }
}

// After flashing button automatically after clicking any keyboard button executution comes here like our game wait till we click on any one of the button
let allButtons = document.querySelectorAll(".btn");
for(button of allButtons){
    button.addEventListener("click", buttonPress);
};

function reset(){
    isStarted = false;
    gameSeq = [];
    userSeq = [];
    level = 0;
}